### ISSUE TITLE
v1.0-OW vs v2.0.0

### ISSUE THREAD

**Issue by Samahu** [nasa/GSAP#146]
Hi, I am a member of OceanWATERS team and we were considering to upgrade our usage of GSAP to v2.0.0. However, while checking the git log for GSAP it seems that v1.0-OW is more recent than v2.0.0 and more up to date. Does that mean that we should stick to v1.0-OW?

**Comment by teubert** [comment]
That's right. You should probably stick with v1.0-OW for now. It's more up to date than 2.0.0. The v1.0-OW is supposed to be a stable point before the next release.

**Comment by Samahu** [comment]
Got it thanks!
