### ISSUE TITLE
Watts, timestamps and the prognoser step function?

### ISSUE THREAD

**Issue by Samahu** [nasa/GSAP#147]
Hello,

I have a question on the library behavior when invoking the predictor step method at rates different than 1 second apart and in particular with regard to the watts unit.

Assume the following:
- We have a component with normal power usage of 5 watts, i.e 5 joules/second
- We are only invoking the prognoser every 2 seconds.

The prognoser step method takes a input parameter with the following data type `map<MessageId, Datum<double>>`. The **MessageId** can be {**Watts**, **Voltage**, ...}. The **Datum** structure is pair of a **value** and a **timestamp**.

Now, the fact that we are invoking the prognoser predict method 2 seconds apart, this means that timestamps would be 2 seconds apart between successive calls.

Having these in mind, my question is what value should we use for the Watts between successive calls?

What ever the answer the first question is, do we treat different metrics (e.g. temperature, voltage, ..) in same or different manner?

Thanks!

**Comment by jason-watkins** [comment]
The data values should represent an instantaneous measurement taken at the associated timestamp. So for a system that is consistently drawing 5 Watts, the `datum.value` field should be 5, regardless of time between measurements.

**Comment by Samahu** [comment]
Got it, thanks for clarifying that
